app: deckoptimmizer
org: mirkovanw
service: deckoptimmizer

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-central-1

functions:
  optimize:
    handler: handler.optimize
    layers:
      - { Ref: GifsicleLambdaLayer }
    url: true
    environment:
      BUCKET: ${param:bucket}
      KEY_ID: ${param:keyId}
      KEY_SECRET: ${param:keySecret}

layers:
  gifsicle:
    path: layer